# --- Frontend Build Stage ---
FROM node:22-alpine AS builder

WORKDIR /app/frontend

# Copy package manifests.
# Assumes package-lock.json has been generated by running 'npm install' locally.
COPY frontend/package.json frontend/package-lock.json ./

# Install dependencies cleanly from lock file
RUN npm ci

# Copy the rest of the frontend source code
COPY frontend/ ./
RUN npm run build

# --- Final App Stage (Standalone Docker) ---
FROM python:3.12-slim

WORKDIR /app

# Prevent Python from writing .pyc files
ENV PYTHONDONTWRITEBYTECODE=1

# Ensure logs are output immediately to the terminal
ENV PYTHONUNBUFFERED=1

# Copy built frontend from builder stage
COPY --from=builder /app/dist ./dist

# Install Python dependencies
COPY requirements.txt .
RUN apt-get update && apt-get install -y --no-install-recommends gcc g++ \
    && pip install --no-cache-dir -r requirements.txt \
    && apt-get purge -y --auto-remove gcc g++ \
    && rm -rf /var/lib/apt/lists/*

# Copy migration scripts and configuration
COPY migrations /app/migrations
COPY alembic.ini .

# Copy the rest of the application
COPY backend /app/backend

ENV APP_PORT=8099
EXPOSE 8099

COPY run.sh .
RUN chmod +x run.sh
CMD ["sh", "run.sh"]