"""initial_schema

Revision ID: 04a7fe6e0718
Revises: 
Create Date: 2026-04-12 20:24:23.116168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04a7fe6e0718'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ir_automations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('allow_parallel', sa.Boolean(), nullable=True),
    sa.Column('ha_expose_button', sa.Boolean(), nullable=True),
    sa.Column('triggers', sa.JSON(), nullable=True),
    sa.Column('actions', sa.JSON(), nullable=True),
    sa.Column('ordering', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ir_devices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('target_bridges', sa.JSON(), nullable=True),
    sa.Column('allowed_bridges', sa.JSON(), nullable=True),
    sa.Column('ordering', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('irdb_remotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    with op.batch_alter_table('irdb_remotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_irdb_remotes_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_irdb_remotes_provider'), ['provider'], unique=False)

    op.create_table('ir_buttons',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('is_output', sa.Boolean(), nullable=True),
    sa.Column('is_input', sa.Boolean(), nullable=True),
    sa.Column('is_event', sa.Boolean(), nullable=True),
    sa.Column('input_mode', sa.String(), nullable=True),
    sa.Column('input_off_delay_s', sa.Integer(), nullable=True),
    sa.Column('ordering', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['ir_devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('irdb_buttons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('remote_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['remote_id'], ['irdb_remotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('irdb_buttons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_irdb_buttons_remote_id'), ['remote_id'], unique=False)

    op.create_table('ir_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('button_id', sa.String(), nullable=False),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('raw_tolerance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['button_id'], ['ir_buttons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ir_codes')
    with op.batch_alter_table('irdb_buttons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_irdb_buttons_remote_id'))

    op.drop_table('irdb_buttons')
    op.drop_table('ir_buttons')
    with op.batch_alter_table('irdb_remotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_irdb_remotes_provider'))
        batch_op.drop_index(batch_op.f('ix_irdb_remotes_name'))

    op.drop_table('irdb_remotes')
    op.drop_table('ir_devices')
    op.drop_table('ir_automations')
    # ### end Alembic commands ###
